language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add clippy

script:
  - cargo clippy --verbose
  - cargo test --verbose

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
